/// Clinical classification dimension. Grain: one row per APR-DRG severity × risk of mortality combination. Contains APR severity levels (Minor/Moderate/Major/Extreme) and risk of mortality descriptions. Also serves as a measure container for peer group median calculations.
table Dim_ClinicalClass
	lineageTag: d9d210df-7172-4ab6-9dc0-9f46d270c13c

	/// Median SMI across facilities in selected peer group. Requires peer group in filter context.
	measure 'PeerGroup Severity Median' = ```
			
			VAR CurrentPeerGroup =
			    SELECTEDVALUE ( Dim_Facility[PeerGroup_Name] )
			RETURN
			CALCULATE (
			    MEDIANX (
			        VALUES ( Dim_Facility[Facility_Key] ),
			        [Severity Mix Index]
			    ),
			    ALL ( Dim_Facility ),
			    Dim_Facility[PeerGroup_Name] = CurrentPeerGroup
			)
			
			```
		formatString: 0.00
		displayFolder: Severity
		lineageTag: 749a10eb-083d-4033-95ae-db75a0122d08

	/// Peer group SMI median that works per facility row. Removes facility filter to calculate median across peer group.
	measure 'PeerGroup Severity Median (FacilitySafe)' = ```
			
			VAR FacilitiesInSelectedPeerGroups =
			    CALCULATETABLE(
			        VALUES(Dim_Facility[Facility_Key]),
			        REMOVEFILTERS(Dim_Facility)   -- removes current facility row
			    )
			RETURN
			MEDIANX(
			    FacilitiesInSelectedPeerGroups,
			    CALCULATE([Severity Mix Index], REMOVEFILTERS(Dim_Facility))
			)
			
			```
		displayFolder: Severity
		lineageTag: 6a3a98ae-92a4-43be-af65-0d81efe6d655

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Peer group SMI median safe for matrix visuals with peer group on rows. Uses bridge table for peer group lookup.
	measure 'PeerGroup Severity Median (RowSafe)' = ```
			
			VAR pg =
			    SELECTEDVALUE(Bridge_Facility_PeerGroup[PeerGroup_Key])
			RETURN
			CALCULATE(
			    MEDIANX(VALUES(Dim_Facility[Facility_Key]), [Severity Mix Index]),
			    REMOVEFILTERS(Dim_Facility[Facility_Key]),
			    KEEPFILTERS(Bridge_Facility_PeerGroup[PeerGroup_Key] = pg)
			)
			
			```
		displayFolder: Severity
		lineageTag: 25648691-c9c5-4e64-a400-2cda0f095649

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Peer group SMI median safe for grouped contexts. Preserves only peer group filter.
	measure 'PeerGroup Severity Median (PeerGroup safe)' = ```
			
			CALCULATE(
			    MEDIANX(
			        VALUES( Dim_Facility[Facility_Key] ),
			        [Severity Mix Index]
			    ),
			    ALLEXCEPT( Dim_Facility, Dim_Facility[PeerGroup_Name] )
			)
			
			```
		displayFolder: Severity
		lineageTag: ee917a44-5fcd-4d89-843e-5bf5597eda24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Median UA rate across facilities in selected peer group. Requires single peer group in filter context; otherwise returns blank.
	measure 'PeerGroup UA Rate Median' = ```
			
			VAR pg = SELECTEDVALUE(Dim_Facility[PeerGroup_Name])
			RETURN
			IF(
			    NOT ISBLANK(pg),
			    CALCULATE(
			        MEDIANX(
			            VALUES(Dim_Facility[Facility_Key]),
			            [Unplanned Admission Rate]
			        ),
			        ALL(Dim_Facility),
			        Dim_Facility[PeerGroup_Name] = pg
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Unplanned
		lineageTag: 9f68e053-c2b3-46ba-bdca-2204372564bf

	/// Peer group UA rate median that works per facility row. Removes facility filter to calculate median across peer group.
	measure 'PeerGroup UA rate Median (FacilitySafe)' =
			
			VAR FacilitiesInSelectedPeerGroups =
			    CALCULATETABLE(
			        VALUES(Dim_Facility[Facility_Key]),
			        REMOVEFILTERS(Dim_Facility)   -- removes current facility row
			    )
			RETURN
			MEDIANX(
			    FacilitiesInSelectedPeerGroups,
			    CALCULATE([Unplanned Admission Rate], REMOVEFILTERS(Dim_Facility))
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Unplanned
		lineageTag: d23bd079-9eb3-4aee-a277-d7c7025895e7

	/// Peer group UA rate median safe for grouped contexts. Preserves only peer group filter.
	measure 'PeerGroup UA rate Median (PeerGroup safe)' =
			
			CALCULATE(
			    MEDIANX(
			        VALUES( Dim_Facility[Facility_Key] ),
			        [Unplanned Admission Rate]
			    ),
			    ALLEXCEPT( Dim_Facility, Dim_Facility[PeerGroup_Name] )
			)
		displayFolder: Unplanned
		lineageTag: 8fe1e9d0-ce6f-478b-906f-bf0bce599720

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Median average LOS across facilities in selected peer group. Requires single peer group in filter context; otherwise returns blank.
	measure 'PeerGroup LOS Median' = ```
			
			IF(
			    HASONEVALUE(Dim_Facility[PeerGroup_Name]),
			    VAR pg = SELECTEDVALUE(Dim_Facility[PeerGroup_Name])
			    RETURN
			        CALCULATE(
			            MEDIANX(VALUES(Dim_Facility[Facility_Key]), [AVG LOS]),
			            REMOVEFILTERS(Dim_Facility[Facility_Name]),
			            Dim_Facility[PeerGroup_Name] = pg
			        )
			)
			
			
			```
		displayFolder: LOS
		lineageTag: 520587b8-54db-4d1a-98ee-e9bfc322cd55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Peer group LOS median that works per facility row. Uses bridge table lookup to find peer group without requiring peer group in filter.
	measure 'PeerGroup LOS Median (FacilitySafe)' = ```
			
			MEDIANX(
			    CALCULATETABLE(
			        VALUES(Dim_Facility[Facility_Key]),
			        REMOVEFILTERS(Dim_Facility[Facility_Name])   -- or Facility_Key
			    ),
			    CALCULATE([AVG LOS], REMOVEFILTERS(Dim_Facility[Facility_Name]))
			)
			
			
			```
		displayFolder: LOS
		lineageTag: ab6bd11d-b7b2-4401-abe7-02282f22cce2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Peer group LOS median safe for grouped contexts. Preserves only peer group filter, removing facility-level filters.
	measure 'PeerGroup LOS Median (PeerGroup safe)' = ```
			
			-- one value per peer group, safe in grouped contexts
			CALCULATE(
			    MEDIANX(
			        VALUES(Dim_Facility[Facility_Key]),
			        CALCULATE([AVG LOS])
			    ),
			    ALLEXCEPT(
			        Dim_Facility,
			        Dim_Facility[PeerGroup_Name]
			    )
			)
			
			```
		displayFolder: LOS
		lineageTag: 1848f604-66b4-4a65-ab4a-c466b6003a17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Peer group margin pressure median safe for grouped contexts. Preserves only peer group filter.
	measure 'PeerGroup Margin Median (PeerGroup safe)' =
			
			-- one value per peer group, safe in grouped contexts
			CALCULATE(
			    MEDIANX(
			        VALUES(Dim_Facility[Facility_Key]),
			        CALCULATE([Margin Pressure])
			    ),
			    ALLEXCEPT(
			        Dim_Facility,
			        Dim_Facility[PeerGroup_Name]
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: C&M P
		lineageTag: f9e9adea-68f6-46da-bb31-6a69055ccc14

	/// Median cost-to-charge ratio across facilities in selected peer group. Requires single peer group in filter context; otherwise returns blank.
	measure 'PeerGroup Margin Pressure Median' =
			
			VAR CurrentPG = SELECTEDVALUE(Dim_Facility[PeerGroup_Name])
			RETURN
			IF(
			    NOT ISBLANK(CurrentPG),
			    CALCULATE(
			        MEDIANX(
			            VALUES(Dim_Facility[Facility_Key]),
			            [Margin Pressure]
			        ),
			        REMOVEFILTERS(Dim_Facility[Facility_Key]),
			        REMOVEFILTERS(Dim_Facility[Facility_Name]),
			        Dim_Facility[PeerGroup_Name] = CurrentPG
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: C&M P
		lineageTag: a87336ee-141e-4def-afb0-a8e98dbd6468

	column ClinicalClass_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4d95719-92a6-47b6-a60c-ce25f9af9277
		summarizeBy: none
		sourceColumn: ClinicalClass_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column APR_DRG_Code
		dataType: string
		isHidden
		lineageTag: 432c47cf-05e1-422b-8a15-4055fc3fb9ae
		summarizeBy: none
		sourceColumn: APR_DRG_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_DRG_Description
		dataType: string
		isHidden
		lineageTag: 75ec9d11-c4d0-43e4-a324-48e85da30d35
		summarizeBy: none
		sourceColumn: APR_DRG_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_Severity_Code
		dataType: int64
		formatString: 0
		lineageTag: e9be9626-2f80-49df-8565-7a17effccc60
		summarizeBy: none
		sourceColumn: APR_Severity_Code

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column APR_Severity_Description
		dataType: string
		lineageTag: 08422a04-96fa-4e02-87cd-32b3e4f07c65
		summarizeBy: none
		sourceColumn: APR_Severity_Description
		sortByColumn: APR_Severity_Code

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column APR_Risk_Of_Mortality_Desc
		dataType: string
		lineageTag: af507df1-9c72-4360-8e08-0033cdf0cb2c
		summarizeBy: none
		sourceColumn: APR_Risk_Of_Mortality_Desc
		sortByColumn: APR_ROM_Sort

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column APR_MDC_Code
		dataType: string
		isHidden
		lineageTag: 7803ead4-3258-466f-b3fb-e35ec83f8759
		summarizeBy: none
		sourceColumn: APR_MDC_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_MDC_Description
		dataType: string
		isHidden
		lineageTag: 14c8ca7f-b252-466e-8435-709d029434af
		summarizeBy: none
		sourceColumn: APR_MDC_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_ROM_Sort
		dataType: int64
		formatString: 0
		lineageTag: 344fb984-7795-47b2-b895-4a07d60c4ea9
		summarizeBy: none
		sourceColumn: APR_ROM_Sort

		annotation SummarizationSetBy = Automatic

	partition Dim_ClinicalClass = m
		mode: import
		source = ```
				let
				    Source = Sql.Database("DESKTOP-3O401KK", "LI_NYHealth", [HierarchicalNavigation=true]),
				    dbo = Source{[Schema="dbo"]}[Data],
				    Dim_ClinicalClass1 = dbo{[Name="Dim_ClinicalClass"]}[Data],
				    AddedROMSort = Table.AddColumn(Dim_ClinicalClass1, "APR_ROM_Sort", each 
				        if [APR_Risk_Of_Mortality_Desc] = "Minor" then 1
				        else if [APR_Risk_Of_Mortality_Desc] = "Moderate" then 2
				        else if [APR_Risk_Of_Mortality_Desc] = "Major" then 3
				        else if [APR_Risk_Of_Mortality_Desc] = "Extreme" then 4
				        else 999, Int64.Type)
				in
				    AddedROMSort
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

