table Dim_ClinicalClass
	lineageTag: d9d210df-7172-4ab6-9dc0-9f46d270c13c

	measure 'PeerGroup Severity Median' = ```
			
			VAR CurrentPeerGroup =
			    SELECTEDVALUE ( Dim_Facility[PeerGroup_Name] )
			RETURN
			CALCULATE (
			    MEDIANX (
			        VALUES ( Dim_Facility[Facility_Key] ),
			        [Severity Mix Index]
			    ),
			    ALL ( Dim_Facility ),
			    Dim_Facility[PeerGroup_Name] = CurrentPeerGroup
			)
			
			```
		formatString: 0.00
		lineageTag: 749a10eb-083d-4033-95ae-db75a0122d08

	measure 'PeerGroup Severity Median (FacilitySafe)' = ```
			
			VAR FacilitiesInSelectedPeerGroups =
			    CALCULATETABLE(
			        VALUES(Dim_Facility[Facility_Key]),
			        REMOVEFILTERS(Dim_Facility)   -- removes current facility row
			    )
			RETURN
			MEDIANX(
			    FacilitiesInSelectedPeerGroups,
			    CALCULATE([Severity Mix Index], REMOVEFILTERS(Dim_Facility))
			)
			
			```
		lineageTag: 6a3a98ae-92a4-43be-af65-0d81efe6d655

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PeerGroup Severity Median (RowSafe)' = ```
			
			VAR pg =
			    SELECTEDVALUE(Bridge_Facility_PeerGroup[PeerGroup_Key])
			RETURN
			CALCULATE(
			    MEDIANX(VALUES(Dim_Facility[Facility_Key]), [Severity Mix Index]),
			    REMOVEFILTERS(Dim_Facility[Facility_Key]),
			    KEEPFILTERS(Bridge_Facility_PeerGroup[PeerGroup_Key] = pg)
			)
			
			```
		lineageTag: 25648691-c9c5-4e64-a400-2cda0f095649

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PeerGroup Severity Median (PeerGroup safe)' = ```
			
			CALCULATE(
			    MEDIANX(
			        VALUES( Dim_Facility[Facility_Key] ),
			        [Severity Mix Index]
			    ),
			    ALLEXCEPT( Dim_Facility, Dim_Facility[PeerGroup_Name] )
			)
			
			```
		lineageTag: ee917a44-5fcd-4d89-843e-5bf5597eda24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ClinicalClass_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4d95719-92a6-47b6-a60c-ce25f9af9277
		summarizeBy: none
		sourceColumn: ClinicalClass_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column APR_DRG_Code
		dataType: string
		isHidden
		lineageTag: 432c47cf-05e1-422b-8a15-4055fc3fb9ae
		summarizeBy: none
		sourceColumn: APR_DRG_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_DRG_Description
		dataType: string
		isHidden
		lineageTag: 75ec9d11-c4d0-43e4-a324-48e85da30d35
		summarizeBy: none
		sourceColumn: APR_DRG_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_Severity_Code
		dataType: int64
		formatString: 0
		lineageTag: e9be9626-2f80-49df-8565-7a17effccc60
		summarizeBy: none
		sourceColumn: APR_Severity_Code

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = User

	column APR_Severity_Description
		dataType: string
		lineageTag: 08422a04-96fa-4e02-87cd-32b3e4f07c65
		summarizeBy: none
		sourceColumn: APR_Severity_Description
		sortByColumn: APR_Severity_Code

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column APR_Risk_Of_Mortality_Desc
		dataType: string
		isHidden
		lineageTag: af507df1-9c72-4360-8e08-0033cdf0cb2c
		summarizeBy: none
		sourceColumn: APR_Risk_Of_Mortality_Desc

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_MDC_Code
		dataType: string
		isHidden
		lineageTag: 7803ead4-3258-466f-b3fb-e35ec83f8759
		summarizeBy: none
		sourceColumn: APR_MDC_Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column APR_MDC_Description
		dataType: string
		isHidden
		lineageTag: 14c8ca7f-b252-466e-8435-709d029434af
		summarizeBy: none
		sourceColumn: APR_MDC_Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_ClinicalClass = m
		mode: import
		source =
				let
				    Source = Sql.Database("DESKTOP-3O401KK", "LI_NYHealth", [HierarchicalNavigation=true]),
				    dbo = Source{[Schema="dbo"]}[Data],
				    Dim_ClinicalClass1 = dbo{[Name="Dim_ClinicalClass"]}[Data]
				in
				    Dim_ClinicalClass1

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

